### ISSUE TITLE
[jwk] please add key type attribute/method

### ISSUE THREAD

**Issue by alonbl** [authlib/joserfc#13]
Hi,

It would be great if the jwk key object will know what type it is so we could have something like:

```diff
        token = joserfc.jwt.encode(
            header={
-               "alg": "RS256",  # guess
+               "alg": jwk1.alg(),
                "kid": jwk1.thumbprint(),
            },
            claims=claims,
            key=jwk1,
        )
```

It was also missing in authlib.

I tried to use `jwk1.get("alg")` but this returns None in most of the cases, I am unsure where is the right place to add this.

Thanks!

**Comment by lepture** [comment]
Hi, if `jwk1.get("alg")` is None, then the key doesn't declare it's "alg" value. If your JWK has a `alg` value, it shouldn't return None.

When you import the key, you can pass a `alg` value:

```python
key = RSAKey.import_key(pem_bytes, {"alg": "RS256"})

key.get('alg')  # => RS256
```

**Comment by lepture** [comment]
I've added a `alg` property on key mode.

**Comment by alonbl** [comment]
Hello @lepture ,

Thank you for addressing the issue, I began writing a patch just like you merged... but it did not work for me... so I opened this ticket as I could not keep up with the hierarchy.

Please try the following, you will notice that the return value is `None`.

Thanks,
Alon

---

```python
import joserfc.jwk

def main():
    jwk1 = joserfc.jwk.RSAKey.generate_key(
        key_size=2048,
        private=True,
    )
    print(jwk1.alg)

if __name__ == '__main__':
    main()
```

**Comment by lepture** [comment]
When generate a key, you can pass "parameters" with the "alg":

```
RSAKey.generate_key(..., parameters={"alg": "RS256"})
```

**Comment by alonbl** [comment]
> When generate a key, you can pass "parameters" with the "alg":

but why would I want to do that? it will lead to inconsistency...

```python
    jwk1 = joserfc.jwk.RSAKey.generate_key(
        key_size=2048,
        private=True,
    )
```

The class has all required information to know that it is `RSA` -> `RS` and 2048 -> 256.

**Comment by lepture** [comment]
I know what you mean now. But a RSAKey can also be used in JWE. We can only determine the alg value if it has a "use" value.
