### ISSUE TITLE
ValueError: This key may not be safe to import when decoding RS256 encoded JWT

### ISSUE THREAD

**Issue by nextmat** [authlib/joserfc#17]
When I use JWT decoding with a RS256 encoded pub key:

```
jwt.decode(token, pub_key)
```

I get `*** ValueError: This key may not be safe to import`. This seems to originate in [import_from_bytes](https://github.com/authlib/joserfc/blob/6741f5ddccb45be964c1c73afcde4a06f96f4c74/src/joserfc/rfc7518/oct_key.py#L32) which checks the key prefix against [this constant](https://github.com/authlib/joserfc/blob/6741f5ddccb45be964c1c73afcde4a06f96f4c74/src/joserfc/rfc7518/oct_key.py#L13).

Since `-----BEGIN` is in this list, it seems like no PEM-formatted keys would work with joserfc?

This key works fine with PyJWT and I'm a bit confused by what the problem is. What is the risk here?

Thanks!

**Comment by lepture** [comment]
@nextmat you need to specify the key with:

```
key = RSAKey.import_key(pub_key)
```

**Comment by nextmat** [comment]
This solved my problem, thank you!
