### ISSUE TITLE
Raise exception for expired JWTs?

### ISSUE THREAD

**Issue by nextmat** [authlib/joserfc#18]
One thing I noticed when migrating some existing code from PyJWT to joserfc is that PyJWT checks the expiration of the token and raises an exception (`ExpiredSignatureError`) if expired while joserfc currently requires you to check this manually.

Would this be a valuable feature addition for joserfc?

**Comment by lepture** [comment]
Currently, you need to use `JWTClaimsRegistry` to validate claims.

https://jose.authlib.org/en/dev/migrations/pyjwt/#verify-exp

**Comment by nextmat** [comment]
Ah excellent. I didn't understand this before, very helpful. Thanks!

**Comment by jashwant** [comment]
This is really crucial and should be part of readme that it won't throw error on expired token unless you specifically validate it.
I am using jose as part of authlib and here's how I am validating.

````python
from authlib.jose import jwt

payload = jwt.decode(token, 'SECRET_KEY')
payload.validate()
