### ISSUE TITLE
Git commit for tag 0.10.0 is not signed

### ISSUE THREAD

**Issue by yan12125** [authlib/joserfc#22]
Hi, I'm the maintainer of Arch Linux package [python-joserfc](https://archlinux.org/packages/extra/any/python-joserfc/). I noticed that git commits corresponding to tags <= 0.9.0 are signed by the GPG key `72F8E895A70CEBDF4F2ADFE07E55E3E0118B2B4C`, while the git commit for tag 0.10.0 is not signed. Is it intended that the new commit is not signed?

In Arch Linux, we try to make sure sources used for packages are authenticated. If a new version cannot be verified with the same keys, it cannot be made sure that the new version is created by the same author as previous layers.

**Comment by lepture** [comment]
@yan12125 It is because I used a new machine without GPG yet.

**Comment by yan12125** [comment]
Got it. Do you plan to sign future commits for tags?

**Comment by lepture** [comment]
@yan12125 yeah.

**Comment by yan12125** [comment]
Nice, thanks!
